# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_year', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
